@service-url = http://localhost:4004
@authorizationWhere = {{service-url}}/authorization-where


#### ------------------------------------------------------------------------
# READ ALL Messages (check authorization)
# Expected response HTTP/1.1 200 OK
### -----------------------------------------------------------------------
GET {{authorizationWhere}}/Messages
Authorization: Basic Basic user:user
Accept: application/json

#### ------------------------------------------------------------------------
# CREATE Messages type LABEL and ID = LAB.test3
# Expected response HTTP/1.1 200 OK 
# Received response HTTP/1.1 403 Forbidden
### -----------------------------------------------------------------------
POST {{authorizationWhere}}/Messages
Authorization: Basic admin:admin
Content-Type: application/json

{
    "ID": "LAB.test3",
    "typeMessage": "label",
    "shortText": "create test AAAAAAA",
    "longText": null,
    "statusCode": null
}

#### ------------------------------------------------------------------------
# READ Messages type LABEL and ID = LAB.test2  
# Expected response HTTP/1.1 200 OK 
# Received response HTTP/1.1 200 OK 
### -----------------------------------------------------------------------
GET {{authorizationWhere}}/Messages(ID='LAB.test2',typeMessage='label')
Authorization: Basic user:user
Accept: application/json

#### ------------------------------------------------------------------------
# UPDATE Messages type LABEL and ID = LAB.test2  
# Expected response HTTP/1.1 403 Forbidden
# Received response HTTP/1.1 403 Forbidden
### -----------------------------------------------------------------------
PATCH {{authorizationWhere}}/Messages(ID='LAB.test2',typeMessage='label')
Authorization: Basic user:user
Content-Type: application/json

{
  "shortText": "test alice AAAAAAA"
}

#### ------------------------------------------------------------------------
# UPDATE Messages type LABEL and ID = LAB.test2  
# Expected response HTTP/1.1 200 OK 
# Received response HTTP/1.1 200 OK
### -----------------------------------------------------------------------
PATCH {{authorizationWhere}}/Messages(ID='LAB.test2',typeMessage='label') 
Authorization: Basic admin:admin
Content-Type: application/json

{
  "shortText": "test alice AAAAAAA"
}

#### ------------------------------------------------------------------------
# READ Messages type SYSTEMMESSAGE and ID = API.BasicAuthData 
# Expected response HTTP/1.1 200 OK 
# Received response HTTP/1.1 200 OK
### -----------------------------------------------------------------------
GET {{authorizationWhere}}/Messages(ID='API.BasicAuthData',typeMessage='systemMessage')
Authorization: Basic user:user
Accept: application/json

#### ------------------------------------------------------------------------
# UPDATE Messages type SYSTEMMESSAGE and ID = API.BasicAuthData 
# Expected response HTTP/1.1 200 OK 
# Received response HTTP/1.1 404 Not Found
### -----------------------------------------------------------------------
PATCH {{authorizationWhere}}/Messages(ID='API.BasicAuthData',typeMessage='systemMessage')
Authorization: Basic admin:admin
Content-Type: application/json

{
  "shortText": "Empty user name and/or password AAAAAAA"
}

#### ------------------------------------------------------------------------
# CREATE Messages type SYSTEMLABEL and ID = API.test2
# Expected response HTTP/1.1 403 Forbidden
# Received response HTTP/1.1 403 Forbidden
### -----------------------------------------------------------------------
POST {{authorizationWhere}}/Messages
Authorization: Basic admin:admin
Content-Type: application/json

{
    "ID": "API.test2",
    "typeMessage": "systemLabel",
    "shortText": "create test AAAAAAA",
    "longText": null,
    "statusCode": null
}